// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeAttendanceSystemAPI.Models;

[Table("Employee")]
public partial class Employee
{
    [Key]
    public Guid EmployeeID { get; set; }

    [Required]
    [StringLength(100)]
    public string Fullname { get; set; }

    [Column(TypeName = "date")]
    public DateTime Birthday { get; set; }

    [Required]
    [StringLength(4)]
    public string Gender { get; set; }

    [StringLength(11)]
    [Unicode(false)]
    public string PhoneNumber { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Required]
    [StringLength(100)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastUpdatedAt { get; set; }

    [StringLength(100)]
    public string LastUpdatedBy { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<Payroll> Payrolls { get; set; } = new List<Payroll>();

    [InverseProperty("Employee")]
    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    [InverseProperty("Employee")]
    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();
}