// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeAttendanceSystemAPI.Models;

[Table("Payroll")]
public partial class Payroll
{
    [Key]
    public int PayRollID { get; set; }

    [Required]
    [StringLength(20)]
    public string Position { get; set; }

    [Column(TypeName = "money")]
    public decimal BasicSalary { get; set; }

    public Guid EmployeeID { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("Payrolls")]
    public virtual Employee Employee { get; set; }
}