// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeAttendanceSystemAPI.Models;

[Table("RefreshToken")]
public partial class RefreshToken
{
    [Key]
    public int ID { get; set; }

    public Guid UserID { get; set; }

    [StringLength(255)]
    public string Token { get; set; }

    [StringLength(255)]
    public string JwtID { get; set; }

    public bool IsUsed { get; set; }

    public bool IsRevoked { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateExpiry { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("RefreshTokens")]
    public virtual TbUser User { get; set; }
}