// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeAttendanceSystemAPI.Models;

[Table("Report")]
public partial class Report
{
    [Key]
    public int ReportID { get; set; }

    [Required]
    [StringLength(255)]
    public string Title { get; set; }

    [Column(TypeName = "text")]
    public string Description { get; set; }

    public Guid EmployeeID { get; set; }

    [Column(TypeName = "money")]
    public decimal GrossPay { get; set; }

    public int MonthlyReport { get; set; }

    [Required]
    [StringLength(20)]
    public string PaidStatus { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastUpdatedAt { get; set; }

    [StringLength(100)]
    public string LastUpdatedBy { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("Reports")]
    public virtual Employee Employee { get; set; }
}