// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeAttendanceSystemAPI.Models;

[Table("Role")]
public partial class Role
{
    [Key]
    public int RoleID { get; set; }

    [Required]
    [StringLength(20)]
    public string Name { get; set; }

    [Column(TypeName = "text")]
    public string Description { get; set; }
}