// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeAttendanceSystemAPI.Models;

[Table("Shift")]
public partial class Shift
{
    [Key]
    public int ShiftID { get; set; }

    [Required]
    [StringLength(20)]
    public string ShiftName { get; set; }

    public TimeSpan StartTime { get; set; }

    public TimeSpan EndTime { get; set; }

    [InverseProperty("Shift")]
    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();
}