// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeAttendanceSystemAPI.Models;

[Table("TbUser")]
public partial class TbUser
{
    [Key]
    public Guid UserID { get; set; }

    [Required]
    [StringLength(255)]
    public string Fullname { get; set; }

    [Required]
    [StringLength(255)]
    public string Email { get; set; }

    [Required]
    public string Password { get; set; }

    public Guid? EmployeeID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastLoggedIn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastUpdatedAt { get; set; }

    public bool IsManager { get; set; }
    public bool IsActive { get; set; }
}